config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :show] do
    resources :comments, only: [:new, :create]
  end

end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' },
    { id: 8, name: '70代' },
    { id: 9, name: '90代' },
    { id: 10, name: '100代' }
  ]

  include ActiveHash::Associations
  has_many :users
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  with_options presence: true do
    validates :text
    validates :user
    validates :question
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '質問のジャンルを選択してください' },
    { id: 2, name: '日常・生活' },
    { id: 3, name: '自然科学' },
    { id: 4, name: '文化' },
    { id: 5, name: '趣味' },
    { id: 6, name: '歴史' },
    { id: 7, name: '技術' },
    { id: 8, name: '人間' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :questions
  end

app/models/question.rb
class Question < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre


  belongs_to :user
  has_many :comments

  with_options presence: true do
    validates :question
    validates :genre_id,   numericality: { other_than: 1 }
    validates :user
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age

   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :comments

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
    validates :age_id, numericality: { other_than: 1 }
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @question = Question.find(params[:question_id])
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to question_path(@comment.question)
    else
     @question = @comment.question
     @comments = @question.comments
     render template: "questions/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @comment = Comment.new
    @comments = @question.comments.includes(:user)
  end

  private

  def question_params
    params.require(:question).permit(:question, :genre_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/comments/new.html.erb
<div class="main">
  <div class='main-theme' >
    <div class="upper-message">
      <div class=message-user>
        <%= @question.user.nickname %>
      </div>
      <div class="message-date">
        <%= @question.created_at %>
      </div>
    </div>      
    <div class="lower-message">
      <div class="message-content">
        <%= @question.question %>
      </div>
    </div>
  </div>
</div>

<%= form_with(model: @comment, url:question_comments_path, local: true) do |f|%>
  <div class="field">
    <%= f.label :text, "回答" %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit "回答する", class: :form__btn  %>
  </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">The Questions</a></h1>
          <% if user_signed_in? %>
            <div class="user_nav grid-6">
              <span><%= current_user.nickname %>
                <ul class="user__info">
                  <li>
                    <%= link_to "マイページ", "/users/#{current_user.id}" %>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </span>
              <%#= link_to "投稿する", new_questions_path, class: "post" %>
            </div>
          <% else %>
            <div class="grid-6">
              <%= link_to "ログイン", new_user_session_path, class: "post" %>
              <%= link_to "新規登録", new_user_registration_path, class: "post" %>
            </div>
          <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright Pictweet 2020.
      </p>
    </footer>
  </body>
</html>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <%= link_to question_path(question.id) do %>
    <div class="main">
      <div class='main-theme' >
        <div class="upper-message">
          <div class=message-user>
            <%= question.user.nickname %>
          </div>
          <div class="message-date">
            <%= l question.created_at %>
          </div>
        </div>      
        <div class="lower-message">
          <div class="message-content">
            <%= question.question %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<%= link_to(new_question_path, class: 'question-btn') do %>
  <span class='question-btn-text'>問題を作る</span>
  <%#= image_tag 'icon_camera.png' , size: '185x50' ,class: "question-btn-icon" %>
<% end %>

app/views/questions/new.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    問題作成の場
  </h1>
</div>

<%= form_with model: @question, url: questions_path, local: true do |f| %>
  <%= render 'devise/shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">問題入力</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :question, class:"input-default", id:"question", placeholder:"50文字以内で問題を作成しましょう！！", maxlength:"50" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ジャンル</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"age"}) %>
  </div>

  <div class="question-btn">
    <%= f.submit "レッツ出題！！" %>
  </div>
<% end %>

app/views/questions/show.html.erb
<div class="main">
  <div class='main-theme' >
    <div class="upper-message">
      <div class=message-user>
        <%= @question.user.nickname %>
      </div>
      <div class="message-date">
        <%= @question.created_at %>
      </div>
    </div>      
    <div class="lower-message">
      <div class="message-content">
        <%= @question.question %>
      </div>
    </div>
  </div>
</div>

<div class="comment-lists">
  <h2>みんなの回答</h2>
  <% @comments.each do |comment| %>
    <div class="comment-name">
      <%= comment.user.nickname %>
    </div>
    <div class="comment-text">
      <%= comment.text %>
    </div>
  <% end %>
</div>

<%= link_to(new_question_comment_path(@question.id), class: 'question-btn') do %>
  <span class='question-btn-text'>今すぐ回答！！</span>
  <%#= image_tag 'icon_camera.png' , size: '185x50' ,class: "question-btn-icon" %>
<% end %>